spring:
  cloud:
    gcp:
      credentials:
        enabled: false
      project-id: ${GCP_PROJECT_ID:local-project}
      pubsub:
        emulator-host: ${PUBSUB_EMULATOR_HOST:localhost:8085}

  jpa:
    open-in-view: false
